version: '3.8'

services:
#  rust-app:
#    build: .
#    ports:
#      - "${PROMETHEUS_PORT_HTTP:-3030}:3030"
#    environment:
#      RUST_LOG: "info"
#      PROMETHEUS_PORT_HTTP: ${PROMETHEUS_PORT_HTTP:-3030}
#      TRADING_PAIR: ${TRADING_PAIR:-BTCFDUSD}
#    volumes:
#      - ./resources/config.toml:/usr/src/app/resources/config.toml
#    networks:
#      - oracle
  prometeus:
    container_name: prometheus
    image: prom/prometheus
    volumes:
      - ./grafana/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  grafana:
    container_name: grafana
    image: grafana/grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
#networks:
#  oracle:
#    driver: bridge
#    external: false