version: '3.8'

services:
  rust-app:
    build: .
    ports:
      - "${SERVER_PORT_HTTP:-8080}:8080"
    environment:
      RUST_LOG: "info"
      SERVER_PORT_HTTP: ${SERVER_PORT_HTTP:-8080}
      TRADING_PAIR: ${TRADING_PAIR:-BTCFDUSD}
    volumes:
      - ./resources/config.toml:/usr/src/app/resources/config.toml
    networks:
      - oracle
networks:
  oracle:
    driver: bridge