scrape_configs:
  - job_name: 'RingBenchMonitor'
    metrics_path: '/metrics'
    scrape_interval: 1s
    static_configs:
      - targets: ['host.docker.internal:3030']
        labels:
          application: 'RingBenchMonitor Prometheus data'